fn print(var fmt: char*): void;
fn printInt(var num: u64): void;
fn printChar(var num: char): void;
fn allocMem(var size: u64): u64*;
fn freeMem(var ptr: u64*): void;
fn getRand(var max: u64): u64;

fn bubbleSort(var arr: u64*, var n: u64): void {
  for (var i: u64 = 0; i < n - 1; i += 1) {
    for (var j: u64 = 0; j < n - i - 1; j += 1) {
      if (arr[j] > arr[j + 1]) {
        var temp: u64 = arr[j];
        arr[j] = arr[j + 1];
        arr[j + 1] = temp;
      }
    }
  }
}

fn printArr(var arr: u64*, var n: u64): void {
  for (var i: u64 = 0; i < n; i += 1) {
    printInt(arr[i]);
    print(" ");
  }
  print("\n");
}

fn main(): int {
  var arr: u64[5] = [9, 365, 81, 634, 623];
  print("Unordered array: ");
  printArr(arr, 5);
  bubbleSort(arr, 5);
  print("Ordered array: ");
  printArr(arr, 5);
  ret 0;
}