fn print(var fmt: char*): void;
fn printInt(var num: u64): void;
fn printChar(var num: char): void;
fn allocMem(var size: u64): u64*;
fn freeMem(var ptr: u64*): void;
fn getRand(var max: u64): u64;
fn printFmt(var fmt: char*, ...): u64;
fn getInput(var buf: char*, var size: int): char*;

fn printBin(var val: u64, var size: int): void {
  for (var i: int = size; i >= 0; i -= 1) {
    if (val & (1 << i) == 0) {
      print("0");
    } else {
      print("1");
    }
  }
}

fn main(): int {
  var test: u8 = 1;
  if (!test) {
    print("Bollocks mate!\n");
  }
  print("\n");
  ret 0;
}