fn print(var fmt: *char): void;
fn printInt(var num: u64): void;
fn printChar(var chr: char): void;
fn allocMem(var size: u64): *u64;
fn freeMem(var ptr: *u64): void;
fn getRand(var max: u64): u64;
fn printFmt(var fmt: *char, ...): u64;
fn getInput(var buf: *char, var size: int): *char;
fn printBin(var num: u64, var bits: int): void;

fn main(): int {
  var test: *u64[10];
  for (var i: int = 0; i < 10; i += 1) {
    test[i] = allocMem(8);
    @test[i] = i;
  }
  for (var j: int = 0; j < 10; j += 1) {
    printFmt("%ld\n", @test[j]);
  }
  ret 0;
}